# Generated by Django 4.2.3 on 2023-07-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hits",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
    ]
