# Generated by Django 4.2.3 on 2023-07-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_recomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
